# Generated by Django 4.2.11 on 2024-04-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='seat_price',
            field=models.PositiveIntegerField(default=0, verbose_name='seat price'),
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stadium',
            name='logo',
            field=models.ImageField(default='/static/images/logo.png', upload_to='', verbose_name='logo'),
        ),
    ]
