# Generated by Django 4.2.11 on 2024-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_management', '0003_remove_seat_reserved_seats_must_have_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='full_name',
            field=models.CharField(blank=True, default='', verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(blank=True, default=False, verbose_name='is reserved?'),
        ),
    ]
