# Generated by Django 4.2.11 on 2024-04-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
